name: Build RCAI F4SE Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup CMake
      uses: lukka/get-cmake@v3.29.3

    - name: Configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Prepare release files
      run: |
        mkdir release
        copy build\Release\RCAI.dll release\
        copy config\RCAI.ini release\

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/RCAI.dll
          release/RCAI.ini
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
