#!/usr/bin/env python3
"""M4 · Visual suite — "FO4 Next" render preset generator (P1-a).

Emits, per hardware tier:
  data/render/fo4_next_<tier>.json   machine-readable preset (consumed by the
                                     plugin's render subsystem + INI writer)
  data/render/ini/fo4_next_<tier>.ini  User.ini/System.ini fragments mapped to
                                     the real engine variables

P1-a1 upscaling/frame-gen is an *injection slot* (D3D11 proxy chain — the
FSR3/DLSS GamePlug precedent), not an INI key; the preset declares it and the
Windows build binds it. See docs/RENDER_PRESETS.md.

Usage: tools/render_preset.py [--out data/render]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TIERS = {
    "high": {
        "doc": "Target: 4K @ 120 Hz — RTX 4080 / RX 7900 XT class",
        "target": {"width": 3840, "height": 2160, "hz": 120, "vram_gb": 12},
        "upscaler": {"slot": "d3d11_proxy", "mode": "fsr3_frame_gen",
                     "quality": "quality", "fallback": "dlss"},
        "render_scale": 1.0,
        "dynamic_resolution": {"enabled": True, "min": 0.75, "max": 1.0,
                               "target_ms": 8.0},
        "taa": True,
        "lights": {"dynamic_per_frame": 48, "per_pixel": True,
                   "omni_fade_m": 18.0},
        "shadows": {"cascade_splits": 4, "distance_m": 160.0,
                    "soft_pc_f": 2.4, "shadow_map_bias_percent": 2.0},
        "volumetrics": {"enabled": True, "step_count": 96, "scatter": 0.35,
                        "via": "re_shade_or_enb"},
        "grass": {"enabled": True, "max_blades_per_bucket": 120},
        "particles": {"max_decal_per_frame": 400},
        "post": {"bloom": 1.0, "chromatic_aberration": 0.25,
                 "film_grain": 0.08, "fxaa": False},
    },
    "mid": {
        "doc": "Target: 1440p @ 144 Hz — RTX 4070 / RX 7800 XT class",
        "target": {"width": 2560, "height": 1440, "hz": 144, "vram_gb": 12},
        "upscaler": {"slot": "d3d11_proxy", "mode": "fsr3_frame_gen",
                     "quality": "balanced", "fallback": "xess"},
        "render_scale": 0.9,
        "dynamic_resolution": {"enabled": True, "min": 0.70, "max": 0.95,
                               "target_ms": 6.8},
        "taa": True,
        "lights": {"dynamic_per_frame": 40, "per_pixel": True,
                   "omni_fade_m": 15.0},
        "shadows": {"cascade_splits": 3, "distance_m": 120.0,
                    "soft_pc_f": 2.0, "shadow_map_bias_percent": 2.0},
        "volumetrics": {"enabled": True, "step_count": 64, "scatter": 0.30,
                        "via": "re_shade_or_enb"},
        "grass": {"enabled": True, "max_blades_per_bucket": 80},
        "particles": {"max_decal_per_frame": 250},
        "post": {"bloom": 0.9, "chromatic_aberration": 0.2,
                 "film_grain": 0.06, "fxaa": False},
    },
    "low": {
        "doc": "Target: 1080p @ 60 Hz — RX 6600 / GTX 1660 class (stable floor)",
        "target": {"width": 1920, "height": 1080, "hz": 60, "vram_gb": 8},
        "upscaler": {"slot": "d3d11_proxy", "mode": "xess",
                     "quality": "performance", "fallback": "none"},
        "render_scale": 1.0,
        "dynamic_resolution": {"enabled": True, "min": 0.80, "max": 1.0,
                               "target_ms": 15.0},
        "taa": True,
        "lights": {"dynamic_per_frame": 24, "per_pixel": True,
                   "omni_fade_m": 10.0},
        "shadows": {"cascade_splits": 2, "distance_m": 80.0,
                    "soft_pc_f": 1.6, "shadow_map_bias_percent": 3.0},
        "volumetrics": {"enabled": False, "step_count": 0, "scatter": 0.0,
                        "via": "re_shade_or_enb"},
        "grass": {"enabled": True, "max_blades_per_bucket": 40},
        "particles": {"max_decal_per_frame": 120},
        "post": {"bloom": 0.8, "chromatic_aberration": 0.15,
                 "film_grain": 0.04, "fxaa": True},
    },
}

INI_TEMPLATE = """; FO4 Next · {tier} — {doc}
; Generated by tools/render_preset.py — do not hand-edit the fragments.
; Apply to User.ini (display/graphics) and System.ini (shadows/grass/water).

[Display]
iSizeWidth={width}
iSizeHeight={height}
iFullscreen=1
bForceWindowed=0

[Graphics]
bUseThreadedShaderCompilation=1
bEnableAnisotropicFiltering=1
uAnisotropicFilteringLevel=16

[Shadows]
bEnableShadows=1
iShadowMapBiasPercent={shadow_map_bias_percent}
fNearPlaneShadowDepth=0.05
fFarPlaneShadowDepth={distance_m}
fMaxShadowFadeDistance={distance_m}
bEnableSoftShadows=1
fSoftShadowQuality={soft_pc_f}

[Grass]
bEnableBladeGrass={grass_on}
iMaxBladesPerBucket={max_blades_per_bucket}
fGrassMaxDistance={grass_dist}

[Particles]
iMaxDecalPerFrame={max_decal_per_frame}
bEnableParticleImpacts=1
bEnableRandomParticleBirth=1

[Water]
bEnableWater=1

[General]
; Frame pacing: the plugin's watchdog (P0-a4) clamps to {hz} Hz and the
; upscaler slot (P1-a1) is bound by the D3D11 proxy at launch — not INI.
iPresentInterval=0
"""


def ini_for(tier, spec):
    return INI_TEMPLATE.format(
        tier=tier, doc=spec["doc"],
        width=spec["target"]["width"], height=spec["target"]["height"],
        shadow_map_bias_percent=int(spec["shadows"]["shadow_map_bias_percent"]),
        distance_m=int(spec["shadows"]["distance_m"]),
        soft_pc_f=spec["shadows"]["soft_pc_f"],
        grass_on=1 if spec["grass"]["enabled"] else 0,
        max_blades_per_bucket=spec["grass"]["max_blades_per_bucket"],
        grass_dist=90 if spec["grass"]["max_blades_per_bucket"] >= 80 else 60,
        max_decal_per_frame=spec["particles"]["max_decal_per_frame"],
        hz=spec["target"]["hz"],
    )


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(ROOT / "data" / "render"))
    args = ap.parse_args(argv)
    out = Path(args.out)
    (out / "ini").mkdir(parents=True, exist_ok=True)
    manifest = {"$doc": "FO4 Next render presets (M4 / P1-a). Generated by tools/render_preset.py.",
                "tiers": {}}
    for tier, spec in TIERS.items():
        p = out / f"fo4_next_{tier}.json"
        doc = {"$tier": tier, "$doc": spec["doc"], **spec}
        p.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
        ini = out / "ini" / f"fo4_next_{tier}.ini"
        ini.write_text(ini_for(tier, spec), encoding="utf-8")
        manifest["tiers"][tier] = {
            "preset": f"data/render/fo4_next_{tier}.json",
            "ini": f"data/render/ini/fo4_next_{tier}.ini",
            "target": spec["target"], "upscaler": spec["upscaler"]["mode"],
        }
        print(f"wrote {p.relative_to(ROOT)} + {ini.relative_to(ROOT)}")
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n",
                                       encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT) / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
